# data folder path
data-path="data"

# Chain
genesis-file="genesis.json" # Path to the custom genesis file

# Network
bootnodes = [
    "enode://a6943b162f401c8d51c04626b6ccef95dfdff65498fcedc7b6c44eee01dac0d20cddf4043cd7d37db6900a6a2b3b94c9abc9bb5e8426ff405b9f3c6f076ea809@18.214.25.163:30303",
    "enode://2b904741c7c8e4700fc497f9fb2c2da4ed0df92b4a24ed239b030d74f1034e2978af50f0cb40099d36d10f7f0a4ce049f7ad2182d5057c38ed90464b9c5346ea@44.204.111.30:30303"
]
p2p-port=30303
max-peers=100
host-allowlist=["*"]

# RPC setup
rpc-http-cors-origins=["all"] 
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=9545
rpc-ws-enabled=true
# NOTE: QBFT should not be available for public rpc enabled nodes
# rpc-http-api=["ETH", "NET", "WEB3", "TXPOOL", "TRACE", "QBFT"] # QBFT ENABLED
rpc-http-api=["ETH", "NET", "WEB3", "TXPOOL", "TRACE"] # QBFT DISABLED


# ETHSTATS
ethstats="XDX-[CLOUD]-[ID]:Q1w2r4t5y6p09aqw8@62.169.20.152:3000"
# ethstats-contact=""
